# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, verbose_name='Имя')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('day_start_datetime', models.TimeField(blank=True, null=True, verbose_name='Время начала рабочего дня')),
                ('day_end_datetime', models.TimeField(blank=True, null=True, verbose_name='Время окончания рабочего дня')),
                ('card_number', models.CharField(max_length=50, null=True, verbose_name='Номер карты')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skud.Department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSummaryDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_delay', models.FloatField(blank=True, null=True)),
                ('hours_way_out', models.FloatField(blank=True, null=True)),
                ('hours_duration', models.FloatField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skud.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skud.Employee')),
            ],
            options={
                'verbose_name': 'Summary по сотруднику за день',
                'verbose_name_plural': 'Summary по сотрудникам за день',
            },
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Время события')),
                ('controller', models.CharField(choices=[('Z5R-Net 2k [40251]', 'Нижняя дверь'), ('Z5R-Net 2k [30964]', 'Верхняя дверь')], max_length=20, verbose_name='Контроллер')),
                ('action_type', models.CharField(choices=[('вход', 'Вход'), ('выход', 'Выход')], max_length=5, verbose_name='Действие')),
                ('card_number', models.CharField(max_length=100, verbose_name='Номер карты')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Сырые данные: событие',
                'verbose_name_plural': 'Сырые данные: события',
            },
        ),
    ]
