# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='patronymic',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='surname',
        ),
    ]
