# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skud', '0002_auto_20171016_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawevent',
            old_name='second_name',
            new_name='patronymic',
        ),
        migrations.RenameField(
            model_name='rawevent',
            old_name='last_name',
            new_name='surname',
        ),
    ]
