# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skud', '0004_auto_20171017_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesummaryday',
            name='last_exit',
            field=models.TimeField(blank=True, editable=False, null=True, verbose_name='Время последнего выхода'),
        ),
    ]
